// Regenerate src/engine/subtypes.ts from the card database: every word after "—" in any type line (cards and tokens).
//   npx tsx scripts/gen-subtypes.ts
import { readFileSync, writeFileSync } from 'node:fs';
const db = JSON.parse(readFileSync(new URL('../data/cards.json', import.meta.url), 'utf8'));
const known = new Set<string>();
const add = (tl: string) => { for (const part of String(tl ?? '').split(' // ')) { const i = part.indexOf('—'); if (i >= 0) for (const w of part.slice(i + 1).trim().toLowerCase().split(/\s+/)) if (/^[a-z'-]+$/.test(w)) known.add(w); } };
for (const c of db.cards) { add(c.typeLine); for (const f of c.faces ?? []) add(f.typeLine); }
for (const t of db.tokens ?? []) add(t.typeLine);
const list = [...known].sort();
writeFileSync(new URL('../src/engine/subtypes.ts', import.meta.url), `// Generated by scripts/gen-subtypes.ts from data/cards.json — every real subtype (creature, land, artifact, …).\n// The filter parser only treats a word as a subtype if it is in this list, so ordinary words never become fake types.\nexport const SUBTYPES = new Set<string>(${JSON.stringify(list)});\n`);
console.log(list.length, 'subtypes');
